# Generated by Django 4.2 on 2023-05-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rufus_app", "0012_remove_menu_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dishitem",
            name="name",
        ),
        migrations.AddField(
            model_name="dish",
            name="platos",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
