# Generated by Django 4.2 on 2023-05-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rufus_app", "0014_remove_dishitem_pictogram_id_dishitem_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dish",
            old_name="platos",
            new_name="plato",
        ),
        migrations.AddField(
            model_name="menu",
            name="platos",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
