# Generated by Django 4.2 on 2023-05-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rufus_app", "0015_rename_platos_dish_plato_menu_platos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="platos",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
