# Generated by Django 4.2 on 2023-05-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rufus_app", "0017_alter_menu_platos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="platos",
        ),
    ]
