# Generated by Django 4.2 on 2023-05-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rufus_app", "0018_remove_menu_platos"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="nombre",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
